added html+css
Jaelouss/team-project-watch-charm pull request #6
Opened 2024-11-16 18:02 UTC by Mykhailo-Sizov

Переглянь будь ласка мені щось не подобається щось розміри в мене скачуть! Чекаю коментр щоб пофіксити!

2024-11-16 18:49 UTC, Jaelouss requested changes

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    letter-spacing: -0.02em;
дублювання, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    color: #0C0C0C;
дублювання, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    width: 263px;
ламає респонсив, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    color: #0C0C0C;
дублювання, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    letter-spacing: -0.02em;
дублювання, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    line-height: 125%;
дублювання, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    font-weight: 500;
дублювання, видали

2024-11-16 18:49 UTC, Jaelouss commented on src/css/reviews.css
> +    letter-spacing: -0.02em;
дублювання, видали

2024-11-17 10:10 UTC, Mykhailo-Sizov commented
Привіт! начебто все) на body є маржи з лівої сторони  і  з правої! прибери він псує геометрію

2024-11-17 11:39 UTC, Jaelouss requested changes
в слак відповів

2024-11-17 13:22 UTC, Mykhailo-Sizov commented
Начебто все)

2024-11-17 13:57 UTC, Jaelouss requested changes

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +    margin-bottom: 24px;
font-size: 32px;
add

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +        margin-bottom: 40px;
font-size: 48px;
add

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +            width: calc(100% - 16px) / 2;
del calc

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +            align-items: center;
del align

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +            flex-direction: column;
del direction

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +    letter-spacing: -0.02em;
del

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +    line-height: 110%;
del

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +        flex-direction: column;
del direction

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +        align-items: center;
del align

2024-11-17 13:57 UTC, Jaelouss commented on src/css/reviews.css
> +    display: none;
.tablet, .desktop {display: none}

об'єднай в один запис

2024-11-17 15:16 UTC, Mykhailo-Sizov commented
&&&&????

2024-11-17 15:44 UTC, Jaelouss approved these changes

2024-11-17 15:44 UTC, merged